# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generateThresholds <- function(gene_interaction, threshold_gene, g_min, g_max, k_min, k_max, possible_interactions, model_count_max, threshold_max, h, lambda_min, lambda_max, n_min, n_max, standard_deviation_factor) {
    .Call('_sRACIPE_generateThresholds', PACKAGE = 'sRACIPE', gene_interaction, threshold_gene, g_min, g_max, k_min, k_max, possible_interactions, model_count_max, threshold_max, h, lambda_min, lambda_max, n_min, n_max, standard_deviation_factor)
}

readTopology <- function(gene_interaction, filepath, filename, geneNames) {
    .Call('_sRACIPE_readTopology', PACKAGE = 'sRACIPE', gene_interaction, filepath, filename, geneNames)
}

simulateGRCCpp <- function(gene_interaction, threshold_gene, g_min, g_max, k_min, k_max, interaction_types, model_count_max, threshold_max, h, lambda_min, lambda_max, n_min, n_max, tot_time, sd_multiplier, number_gene, D_max, D_shot_scaling, scaled_noise, D_levels, D_scaling, output_precision, ANNEALING, initial_conditions, filename, print_start, print_interval, integrate = TRUE, genParams = TRUE, genIC = TRUE, stepper = 1L, rk_tolerance = 0.001) {
    .Call('_sRACIPE_simulateGRCCpp', PACKAGE = 'sRACIPE', gene_interaction, threshold_gene, g_min, g_max, k_min, k_max, interaction_types, model_count_max, threshold_max, h, lambda_min, lambda_max, n_min, n_max, tot_time, sd_multiplier, number_gene, D_max, D_shot_scaling, scaled_noise, D_levels, D_scaling, output_precision, ANNEALING, initial_conditions, filename, print_start, print_interval, integrate, genParams, genIC, stepper, rk_tolerance)
}

